name: Claude Integration Test

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Workflow triggered successfully"
